### ISSUE TITLE
Missing pth file

### ISSUE THREAD

**Issue by Malaika68** [huyquoctrinh/KDAS#1]
Where can I find this file path = './pretrained_pth/pvt_v2_b2.pth'?

**Comment by huyquoctrinh** [comment]
Hi, thank you so much for this issue. Can you update the weight file of pvt_v2_b2.pth and pvt_v2_b0.pth in this link, I hope it can help you https://drive.google.com/drive/folders/1AMIXmyCcZTA0IfPTGOrdNjYvmIIfH-Ql?usp=drive_link

**Comment by Malaika68** [comment]
Hello, Thanks for sending this, can you also tell what would be the structure of test dataset? as my currecnt test directory is 
![image](https://github.com/huyquoctrinh/KDAS/assets/74342011/741f389e-ef2b-4209-b73e-5e53dfe3aba1)
but it is giving me the error of FileNotFoundError: [Errno 2] No such file or directory: './dataset/TestDataset/test/masks/'

**Comment by huyquoctrinh** [comment]
Hi, can you check the new data that I have updated, maybe it can help you fix that issue

**Comment by Malaika68** [comment]
Hi Trinh, thanks, for sending this, code is running, also can you tell
where can I find the paper?

**Comment by huyquoctrinh** [comment]
Ah, I am updating the final version on arxiv, it will take 2-3 days. I will have an update until the paper uploading finish. Thanks for considering our work ;)

**Comment by Malaika68** [comment]
Ok, thanks for the update.

**Comment by Malaika68** [comment]
Can you please tell from where the PolyPVT.pth is distilled? how we have got the distilled backbonePolyPVTB0_distilled.pth?

**Comment by huyquoctrinh** [comment]
Hi @Malaika68, the distill version will be in the PolypPVT.pth. The name distilled is just my rename on drive for everyone to get ease to distinguish between every model. I hope this one is okay for you :>

**Comment by Malaika68** [comment]
Thanks for the answer, also my last question would be, where can I get the test results, I ran the file paper_test, but could not find the results metrics anywhere?

**Comment by huyquoctrinh** [comment]
Hi @Malaika68 , sorry for my late response. Regarding the test, you can run the file ```test_paper.py``` to get the segmented mask, and then follow the instruction [UACANET](https://github.com/plemeri/UACANet) for the benchmark.

**Comment by huyquoctrinh** [comment]
Just remember to change the file weight in the argument for update to the distilled model weight. I have just changed the name to prevent the misunderstanding ;)
