### ISSUE TITLE
eval question

### ISSUE THREAD

**Issue by LeonWang0735** [huyquoctrinh/KDAS#3]
I run the command python eval.py --config configs/eval.yaml --verbose
then trigger assertion
![image](https://github.com/user-attachments/assets/c0ee510c-499e-4e6c-a79f-590807968d07)

**Comment by huyquoctrinh** [comment]
Hi @mewbugger , the reason for this problem due to the different shapes of the prediction mask and the ground truth mask. To deal with this problem, you should resize the prediction mask to the same size of the ground truth mask. So it would be solved.

**Comment by LeonWang0735** [comment]
> Hi @mewbugger , the reason for this problem due to the different shapes of the prediction mask and the ground truth mask. To deal with this problem, you should resize the prediction mask to the same size of the ground truth mask. So it would be solved.

thanks for your reply,but different datasets have different shapes,I try to resize the prediction mask to the same size of CVC-300,then the other datasets cant match the shape.
The following image is the result of CVC-300 after I resize it
![image](https://github.com/user-attachments/assets/5865215b-fcc3-4919-9948-2e84af57c852)
Can you udpate the code for this problem,cuz I just follow the readme.
Thank you very much!

**Comment by huyquoctrinh** [comment]
Hi @mewbugger. Thanks alot, I will make an update. Can you share the checkpoint that you ran for this CVC-300 dataset because the current results is quite low. Maybe I can check for the problem of your run

**Comment by LeonWang0735** [comment]
Sorry for the late reply，this is the checkpoint  https://drive.google.com/file/d/18ayCsqBoO1EGuGql0ExCfAqyg5Gy5Omg/view?usp=drive_link

**Comment by LeonWang0735** [comment]
I train the model again,and I resize the prediction mask to the same size of the ground truth mask,the result still quiet low，Is it because the teacher model I used is wrong?
![1725530648155](https://github.com/user-attachments/assets/0e11c881-3c9d-4964-b4b1-59dacea6b55d)
I used this one

**Comment by huyquoctrinh** [comment]
Hi @mewbugger , thank you so much. Can you share with me your training log, maybe we can observe the problem!

**Comment by mewbugger** [comment]
Hhank you so much.this is my training log: https://drive.google.com/file/d/16oJ1hB9cXlADoonqAATPFERt5SG-g7-D/view?usp=drive_link

**Comment by LeonWang0735** [comment]
Thank you so much.This is my training log: https://drive.google.com/file/d/16oJ1hB9cXlADoonqAATPFERt5SG-g7-D/view?usp=drive_link

**Comment by huyquoctrinh** [comment]
Hi, this training log is very nice. I think the problem come from the inference code. I will check your checkpoint!

**Comment by LeonWang0735** [comment]
Thanks!
Actually,I don't understand what the code in test_paper.py below does
![image](https://github.com/user-attachments/assets/6f685931-bb29-455d-97d5-0485a345efd1)
Because the shape of the image output by this code is（352， 3520）
And the code in eval.py below is how I resize the predic_mask
![image](https://github.com/user-attachments/assets/259f90ae-9c03-4663-9e46-3747ab92dabc)

**Comment by huyquoctrinh** [comment]
Hi the first line of code is to reverse the normalized mask in to the actual pixel value of the mask prediction. For the resize function, can you try to change to resize by cv2 and check the output mask, because with the low results, it is likely return nothing in the mask

**Comment by LeonWang0735** [comment]
Thanks.I check my output mask, the output mask becomes a horizontal splicing of 10 pictures, is that right?
![image](https://github.com/user-attachments/assets/f303b863-3bdf-4a8e-97fe-532ab9abbab4)

**Comment by LeonWang0735** [comment]
Hi,I change the code in test_paper to the code below, and result become better but still doesn’t match what’s in the paper：
![image](https://github.com/user-attachments/assets/5a9471a3-c35c-4296-880e-bf6e01a1bbfb)
![image](https://github.com/user-attachments/assets/19552420-be86-400f-b71e-6255f37e03db)
How can I solve the problem?

**Comment by huyquoctrinh** [comment]
Hi @mewbugger , it's good to hear it is better now. What is your result now?

**Comment by LeonWang0735** [comment]
> Hi,I change the code in test_paper to the code below, and result become better but still doesn’t match what’s in the paper： ![image](https://private-user-images.githubusercontent.com/87310790/365005465-5a9471a3-c35c-4296-880e-bf6e01a1bbfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTc3MDUsIm5iZiI6MTcyNTU5NzQwNSwicGF0aCI6Ii84NzMxMDc5MC8zNjUwMDU0NjUtNWE5NDcxYTMtYzM1Yy00Mjk2LTg4MGUtYmY2ZTAxYTFiYmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA0MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYmM1ZmJlYjE1MDU0ZmU5OTBiNTViMGIwN2Q4OTRmN2FkY2RkNjBhODk2YjlhMWIxZDY3MDdmNTIwMTcyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94Bh6kxrTbzmVkjft4BZUyW2LzD6ie59JfJsskI_yCw) ![image](https://private-user-images.githubusercontent.com/87310790/365005801-19552420-be86-400f-b71e-6255f37e03db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1OTc3MDUsIm5iZiI6MTcyNTU5NzQwNSwicGF0aCI6Ii84NzMxMDc5MC8zNjUwMDU4MDEtMTk1NTI0MjAtYmU4Ni00MDBmLWI3MWUtNjI1NWYzN2UwM2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA0MzY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxOWY4OTZiNjljMTU5OWRmYmE0ZGU3N2VlZTliNzc5NmViM2E1NTFjZmYxMmYzYWI0NzhkYTFmYzljYjQ4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gD-A1ckavgGNVTOa4_OjKs0pz83c_npaYS8GVhYi2_o) How can I solve the problem?

Thanks, The result I show in this reply

**Comment by huyquoctrinh** [comment]
Hi @mewbugger , let me have a check and I will let you know !

**Comment by LeonWang0735** [comment]
Thank you very much!

**Comment by huyquoctrinh** [comment]
Hi @mewbugger , I have tried to train again do the benchmark again, it's still similar the same. Below is the results from ETIS and CVC-Clinic DB, first 2 values are MeanDice and meanIOU. I am doing the benchmark on your weight again to find the problem

<img width="626" alt="image" src="https://github.com/user-attachments/assets/fa468657-713c-4c56-90d4-4e111162c02c">
<img width="592" alt="image" src="https://github.com/user-attachments/assets/b9d47d6c-b35e-4b53-a04e-5570d880484f">
